name: Run ML Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and run scripts
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
          python classical_ml/ml_preprocessing.py
          python classical_ml/ml_models.py
